# Generated by Django 4.2.9 on 2024-02-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_auction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_img',
            field=models.URLField(max_length=10000, null=True),
        ),
    ]
