# Generated by Django 4.2.9 on 2024-02-07 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listing_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 22, 26, 4, 636718)),
            preserve_default=False,
        ),
    ]
