# Generated by Django 4.2.9 on 2024-02-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_listing_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='listing_img',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
